<?php
require_once __DIR__ . '/src/SoccerCal.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>US Soccer iCal Feeds</title>
</head>
<link href="styles.css" rel="stylesheet" media="all">
<body>
  <header>
    <img id="crest" src="//cdn-us-ec.yottaa.net/5682eca20b534438800014b5/www.ussoccer.com/v~13.1d/~/media/upload/us-soccer-logo.png?yocs=6_b_&amp;yoloc=us" data-yo-delaytype="lazy" data-yo-src="//cdn-us-ec.yottaa.net/5682eca20b534438800014b5/www.ussoccer.com/v~13.1d/~/media/upload/us-soccer-logo.png?yocs=6_b_&amp;yoloc=us">
    <h1>U.S. Soccer iCal Feeds</h1>
  </header>
  <main>
    <?php print SoccerCal::renderSummaries(); ?>
  </main>
  <footer>
    <p>Feeds are generated by scraping the data from ussoccer.com's schedule pages.</p>
  </footer>
</body>
</html>
